[global_config]
test = "tt"

[documentation]
main = """
Configuration file contains collection of build commands.
Each build command *must* have foolloding fields:
- 'name' :: for human-readable name of the command
- 'ext' :: for file extension
- 'uname' :: for *unique* identifier.
- 'build_command' :: bash shell command to build input file
"""

[[build]]
name = "Python mypy"
uname = "python mypy"
lang = "python"
ext = "py"
type = "interpreted"
build_file = "{{input_file}}"
build_command = "mypy {{input_file}}"
file_globs = [ "{{input_file}}" ]

[[build]]
name = "Nim silent"
ext = "nim"
uname = "nim_silent"
type = "compiled"
build_file = "{{input_file}}.bin"
build_command = """
nim c --cc:tcc --verbosity:0 --hints:off -o:{{build_file}} {{input_file}}"""
file_globs = [ "*.nim" ]
run_command = "./{{build_file}}"

[[build]]
name = "Nim tcc"
ext = "nim"
uname = "nim_tcc"
type = "compiled"
build_file = "{{input_file}}.bin"
build_command = "nim c --cc:tcc -o:'{{build_file}}' '{{input_file}}'"
run_command = "./{{build_file}}"
file_globs = [ "*.nim" ]

[[build]]
name = "Nim simple"
ext = "nim"
type = "compiled"
uname = "nim_simple"
build_file = "{{input_file}}.bin"
build_command = "nim c -o:'{{build_file}}' '{{input_file}}'"
run_command = "./{{build_file}}"
file_globs = [ "{{input_file}}" ]

[[build]]
name = "Nim legacy"
lang = "nim"
type = "compiled"
uname = "nim_legacy"
ext = "nim"
build_file = "{{input_file}}.bin"
build_command = "nim c --cc:tcc --verbosity:0 --hints:off -o:'{{build_file}}' -d:nimOldCaseObjects  --warning[CaseTransition]:off {{input_file}}"
run_command = "./{{build_file}}"
file_globs = [ "{{input_file}}" ]

[[build]]
name = "Clang debug"
ext = "cpp"
uname = "clang_debug"
type = "compiled"
build_file = "{{input_file}}.bin"
build_command = "clang++ --std=c++17  -o {{build_file}}  -g -DDEBUG {{input_file}}"
run_command = "./{{build_file}}"
file_globs = [ "{{input_file}}" ]

[[build]]
name = "Clang release"
lang = "c++"
type = "compiled"
ext = "cpp"
uname = "clang_release"
build_file = "{{input_file}}.bin"
build_command = "clang++ --std=c++17 -o {{build_file}} -O2 {{input_file}}"
run_command = "./{{build_file}}"
file_globs = [ "{{input_file}}" ]


[[build]]
name = "TCC C"
lang = "c"
type = "compiled"
ext = "c"
uname = "tcc_c"
build_file = "{{input_file}}.bin"
build_command = "tcc -o {{build_file}} {{input_file}}"
run_command = "./{{build_file}}"
file_globs = [ "{{input_file}}" ]

[[build]]
name = "G++ json"
lang = "c++"
type = "compiled"
ext = "cpp"
uname = "g++_json"
build_file = "{{input_file}}.bin"
build_command = """
g++ -o {{build_file}} -fdiagnostics-format=json {{input_file}} 2>&1 | \
jq .[].message"""
file_globs = [ "{{input_file}}" ]

[[build]]
name = "Clang++ all"
lang = "c++"
ext = "cpp"
uname = "clang++_all"
type = "compiled"
build_file = "{{input_file}}.bin"
build_command = "clang++  --std=c++17 *.cpp -o {{build_file}}"
file_globs = [ "*.cpp", "*.hpp" ]
run_command = "./{{build_file}}"

[[build]]
name = "Perl critic"
uname = "perl_critic_0"
lang = "perl"
ext = "pl"
build_file = "{{input_file}}"
build_command = ""
file_globs = [ "*.pl" ]
run_command = "./{{build_file}}"


[[build]]
name = "Bash default"
uname = "bash_default_0"
lang = "bash"
ext = "sh"
build_file = "{{input_file}}"
build_command = ""
file_globs = [ "{{input_file}}" ]
run_command = "./{{build_file}}"

[[build]]
name = "Bash shellcheck"
uname = "bash_shellcheck_0"
lang = "bash"
ext = "sh"
build_command = ""
build_fule = "{{input_file}}"
file_globs = [ "{{input_file}}" ]
run_command = "shellcheck {{input_file}} && ./{{input_file}}"

[[build]]
name = "Ocaml simple"
uname = "ocaml_simple"
ext = "ml"
build_file = "{{input_file}}.bin"
build_command = "ocamlc -o {{build_file}} {{input_file}}"
file_globs = [ "{{input_file}}" ]
run_command = "./{{build_file}}"

[[build]]
name = "Java single file"
uname = "java_single_file_1"
ext = "java"
build_file = ".{{input_file}}.d/out.jar"
build_command = """
{{fsm_build_bin_dir}}/build-commands/java.pl {{input_file}}
"""
file_globs = [ "{{input_file}}" ]
run_command = "java -jar {{build_file}}"

[[build]]
name = "Java delayed run"
uname = "java_delayed_run_1"
ext = "java"
build_file = "{{input_file}}.d/out.jar"
build_command = """
{{fsm_build_bin_dir}}/build-commands/java.pl {{input_file}}
"""
file_globs = [ "{{input_file}}" ]
run_command = ""


[[build]]
name = "Java preprocessor no run"
uname = "java_preprocessor_no_run_1"
ext = "java"
build_file = ".{{input_file}}.tmp.d/out.jar"
build_command = """
m4 {{input_file}} > {{input_file}}.tmp && \
{{fsm_build_bin_dir}}/build-commands/java.pl {{input_file}}.tmp && \
mv {{input_file}}.tmp .{{input_file}}.tmp.d/
"""
file_globs = [ "*.java", "*.m4" ]
run_command = ""

[[build]]
name = "java.pl"
uname = "java_pl_1"
ext = "java"
build_file = ".{{input_file}}.d/out.jar"
build_command = """
{{fsm_build_bin_dir}}/build-commands/java.pl {{input_file}}
"""
file_globs = [ "*.java" ]
run_command = "java -jar {{build_file}}"



[[build]]
name = "Java preprocessor do run"
uname = "java_preprocessor_do_run_1"
ext = "java"
build_file = ".{{input_file}}.tmp.d/out.jar"
build_command = """
m4 {{input_file}} > {{input_file}}.tmp && \
{{fsm_build_bin_dir}}/build-commands/java.pl {{input_file}}.tmp && \
mv {{input_file}}.tmp .{{input_file}}.tmp.d/
"""
file_globs = [ "*.java", "*.m4" ]
run_command = "java -jar {{build_file}}"

[[build]]
name = "Latex latexmk pdflua"
uname = "latex_latexmk_pdflua"
ext = "tex"
build_file = "{{input_file}}.pdf"
build_command = "latexmk -latexoption=\"-shell-escape\" -pdflua --interaction=nonstopmode {{input_file}}"
cleanup_command = "latexmk -C {{input_file}}"
run_command = ""

[[build]]
name = "GNU Prolog compile"
uname = "gprolog_compile"
ext = "gplog"
build_file = "{{input_file}}.bin"
build_command = """
cp {{input_file}} {{input_file}}.pl && \
gplc -o {{build_file}} {{input_file}}.pl && \
rm {{input_file}}.pl
"""
run_command = "./{{build_file}}"

[[build]]
name = "SWI prolog simple"
uname = "swi_prolog"
ext = "splog"
build_command = "true"
run_command = "swipl -t main -g halt -f {{input_file}}"


[[build]]
name = "Graphviz simple"
uname = "graphviz_simple"
ext = "dot"
build_file = "{{input_file}}.tmp.png"
build_command = "dot -Tpng {{input_file}} -o{{build_file}}"
run_command = "true"

[[build]]
name = "Graphviz m4"
uname = "graphviz_m4"
ext = "dot"
build_file = "{{input_file}}.tmp.png"
build_command = """
m4 {{input_file}} > {{input_file}}.tmp && \
dot -Tpng {{input_file}}.tmp -o{{build_file}}
"""
run_command = "true"

[[build]]
name = "Emacs elisp"
uname = "emacs_elisp"
ext = "el"
build_command = ""
run_command = "emacs --script {{input_file}}"
