import pegs
import options
import termformat, argparse, helpers
import os, strutils, sequtils, macros
import colecho_lib
import colecho_types
import strformat
import tables
import deques

var level = 0


# let parser = peg "document":
#   document <- +code_block * Skip
#   code_block <- +( if_stmt | for_loop | while_loop )

#   if_stmt <- "if" * Skip * "(" * Skip * expr_primary * Skip * ")" * Skip * brace_stmt:
#     echo "Found if statement"

#   for_loop <- "for" * Skip * "(" * exp * ";" * exp * ";" * exp * ")" * Skip * brace_stmt:
#     echo "Found for loop"

#   while_loop <- "while" * Skip * "(" * Skip * exp * Skip * ")" * Skip * brace_stmt:
#     echo "Found while loop"

#   funccall <- ident * "()" * Skip

#   exp <- expr_primary # To reduce typing
#   brace_stmt <- "{" * Skip * *( code_block ) * Skip * "}"
#   Skip <- *( Blank | Space | '\n' )

#   expr_primary <- expr | ident | constant | expr_decl | "(" * expr * ")"
#   var_decl <- type_spec * Skip * expr_assign

#   expr <- expr_assign | expr_binary | expr_unary | funccall
#   expr_decl <- type_spec * expr_assign
#   expr_assign <- Skip * +Alnum * Skip * oper_assign * Skip * expr
#   expr_binary <- Skip * expr * Skip * oper_binary * Skip * expr
#   expr_unary <- oper_unary * expr
#   type_spec <- ident # TODO

#   ident <- Skip * +Alnum * Skip
#   constant <- Skip * +Digit * Skip
#   oper_assign <- Skip * "=" * Skip
#   oper_unary <- Skip * ( "&" | "*" | "+" | "-" | "~" | "!" ) * Skip
#   oper_binary <- Skip * ( "+" | "<" ) * Skip

# echo parser.match(inputString)

# let pegAst = """
# document <- code_block*
# code_block <- for_loop
# for_loop <- "for" "(" expression ";" expression ";" expression ")" "{" *code_block "}"
# expression <- assign_expr | compare_expr
# assign_expr <- \ident "="
# """

let pegGrammar = readFile("grammar.pegs").string
let pegAst = parsePeg(pegGrammar)



var lvl = 0

let parse = pegAst.eventParser:
  pkNonTerminal:
    enter:
      let ident = "  ".repeat(lvl)
      inc lvl
    leave:
      dec lvl

      let ident = "  ".repeat(lvl)
      if length > 0:
        case p.nt.name:
          of "for_loop", "while_loop", "cond_stmt", "if_stmt":
            echo ident, p.nt.name, " end"

var dbgLvl = 0
var dbgStr = ""
let ignored = @["ws"]

# TODO FIXME dump code generated by template/macro inocation
# macro debugInvocation(head, body: typed): typed =
#   let ast = quote do:
#     `body`

#   result = body

# IDEA write parsing stages to file with moving arrow
# IDEA generate terminal animation from file parsing
proc showArrow(indent: string, topString: string, pos: int, annot: string = "") =
  echo indent, topString
  echo indent, " ".repeat(pos - 1), "^ ", annot

let dumpAll = false

#~#== Debug parser
let debugParse =
  eventParser(pegAst):
    pkNonTerminal:
      enter:
        if (p.nt.name notin ignored or dumpAll):
          let ident = "|   ".repeat(dbgLvl)
          echo ident, &"{p.nt.name}"
          inc dbgLvl
      leave:
        if (p.nt.name notin ignored or dumpAll):
          dec dbgLvl
          let ident = "|   ".repeat(dbgLvl)
          let matchStr = dbgStr.substr(start, start + length - 1)
          if length > 0:
            showArrow(ident, s, start + length, annot =
                      &"[ {p.nt.name} ] " & $toGreen("ok"))
          else:
            echo ident, &"[ {p.nt.name} ] " & $toRed("fail")
    pkChar:
      leave:
        let ident = "    ".repeat(dbgLvl)
        if length > 0:
          echo ident, "[ '", p.ch, "' ]", $toGreen(" ok")
        else:
          echo ident, "[ '", p.ch, "' ]", $toRed(" fail")
    pkTerminal:
      leave:
        let ident = "    ".repeat(dbgLvl)
        if length > 0:
          echo ident, " \"", p.term, "\" ", $toGreen("ok")
        else:
          echo ident, " \"", p.term, "\" ", $toRed("fail")



proc test(str: string, andParse: bool = false, dbg = false): void =
  let res = $(if str.match(pegAst): "true".toGreen else: "false".toRed)
  echo &"{res:<15}: {str}"
  if dbg:
    dbgStr = str
    discard debugParse(str)
  elif andParse:
    discard parse(str)


type
  NodeKind = enum
    cnkIf
    cnkElif
    cnkWhile
    cnkElse
    cnkFor
    cnkCond
    cnkAssgn
    cnkExpr
    cnkUndef
    cnkTerminal



  Node = ref object
    childNodes: seq[Node]
    case kind: NodeKind:
      of cnkIf .. cnkWhile: cond: Option[string]
      of cnkFor:
        init: Option[string]
        bound: Option[string]
        postAct: Option[string]
      else: nil



proc toNodeKind(str: string): NodeKind =
  case str:
    of "if_stmt": cnkIf
    of "elif_stmt": cnkElif
    of "else_stmt": cnkElse
    of "for_loop": cnkFor
    of "while_loop": cnkWhile
    of "cond_stmt": cnkCond
    of "assgn": cnkAssgn
    of "expr": cnkExpr
    else: cnkUndef

proc toNode(str: string): Node = Node(kind: str.toNodeKind)

proc `$`(node: Node): string =
  result = node.mapItBFStoSeq(
    childNodes,
    " ".repeat(lv) & $(it.kind)
  ).join("\n")



type
  Scope = ref object
    node: Node
    name: string
    text: string
    children: seq[Scope]



proc placeChildNode(stack: var seq[Scope], child: Scope) =
  var top = stack.pop()
  var tn = top.node
  let tkind = top.node.kind
  var addAsChild = false
  echoi 1, "Placing child: ", child.text
  case child.node.kind:
    of cnkAssgn:
      if tkind == cnkFor and tn.init.isNone:
        tn.init = child.text
      else:
        addAsChild = true
    of cnkExpr:
      case tkind:
        of cnkFor:
          if tn.bound.isNone:
            tn.bound = child.text
          elif tn.postAct.isNone:
            tn.postAct = child.text
          else:
            addAsChild = true
        of cnkIf .. cnkWhile:
          if tn.cond.isNone:
            tn.cond = child.text
          else:
            addAsChild = true
        else:
          addAsChild = true

    else: addAsChild = true

  top.node = tn

  if addAsChild:
    echoi 2, "As child node for top"
    top.children.add(child)

  stack.add(top)

func getName(st: seq[Scope]): string = tern(st.len == 0, "start_", st[^1].name)

proc chartBuilder(str: string): Option[Scope] =
  echoi "Building chart for: ", str
  var done: bool = false
  var stack: seq[Scope]
  let allowed = @["if_stmt", "while_loop", "expr", "assgn",
                  "for_loop", "elif_stmt", "else_stmt", "cond_stmt"]
  #~# Flowchart parser
  let chartBuilderImpl = pegAst.eventParser:
    pkNonTerminal:
      enter:
        if not done and p.nt.name in allowed:
          # echoi stack.len, &"add {p.nt.name} to stack"
          stack.add(Scope(
            name: getName(stack) & p.nt.name & "_",
            node: toNode(p.nt.name)
          ))
        # elif p.nt.name notin allowed:
        #   echoi 1, "Skipping", p.nt.name
      leave:
        if not done and p.nt.name in allowed:
          if length > 0:
            var child = stack.pop()
            if stack.len > 0:
              child.text = s.substr(start, start + length - 1)
              echoi "found", child.text, child.node.kind
              stack.placeChildNode(child)
            else:
              done = true
              stack.add(child)
          else:
            discard stack.pop()
            # echoi stack.len, &"remove {p.nt.name} from stack"

  let res = chartBuilderImpl(str)
  if res > 0:
    showArrow("", str, res, &"parse: ok ({res})")
    return stack[^1]


# echo parse("if ( )")
# echo parse("for (i = 0;;)")

# proc testr(str: rule, std: text): void =
#   let pnt = pegAst.nt(str)

type
  ScopeDescr = object
    start: string
    final: string
    body: string
    node: Node


type
  GVizNode = ref object
    name: string
    targets: seq[GVizNode]
    style: string
    text: string


func enumerate(scopes: seq[Scope]): seq[Scope] =
  toSeq(pairs(scopes)).mapIt(
    block:
      var res = it.val
      res.name = res.name & "_" & $it.key
      res
  )


proc makeDotNode(stmt: ScopeDescr, name: string, start: bool = true): string =
  echoi level, "Make node for", name
  let shape = case stmt.node.kind:
    of cnkFor:
      "shape=" & (if start: "trapezium" else: "invtrapezium")
    of cnkWhile:
      "shape=" & (if start: "trapezium" else: "point")
    of cnkIf:
      "shape=" & (if start: "diamond" else: "point")
    of cnkElif:
      "shape=" & tern(start, "diamond", "point")
    of cnkElse, cnkCond:
      "shape=point"
    else: ""

  let style = case stmt.node.kind:
    of cnkFor: ""
    else: tern(start, "", "style=bold")

  let label = case stmt.node.kind:
    of cnkIf .. cnkWhile: &"label=\"{stmt.node.cond.get()}\""
    of cnkFor:
      block:
        let nd = stmt.node
        if start:
          if nd.init.isSome and nd.bound.isSome:
            &"label=\"{nd.init.get()}\n{nd.bound.get()}\""
          else: ""
        else:
          if stmt.node.postAct.isSome:
            &"label=\"{stmt.node.postAct.get()}\""
          else: ""
    else: &"label=\"{name}\""

  result = &"{name}[" &
     join(@[shape, label, style
            , &"xlabel=\"{name}\""
     ].filterIt(it != ""), ",") &
     "];\n"

proc joinScope(str, startWith, endWith: string): string =
  result &= startWith & "_body" & "[label=\"" & str & "\"" & ",shape=box];\n"

proc joinScope(
  statements: seq[ScopeDescr],
  startWith: string, endWith: string,
  top: Node
     ): string =
  var prevEnd = startWith
  echoi level, "Joining scope under", startWith
  echoi level, "To", endWith
  inc level
  if top.kind == cnkCond:
    for stmt in statements:
      if stmt.node.kind notin @[cnkIf, cnkElif, cnkElse, cnkCond]:
        ceUserError0("stmt child is not if/else/elif")


    var branches: string

    for stmt in statements:
      result &= stmt.makeDotNode(stmt.start, true)
      result &= stmt.makeDotNode(stmt.final, false)
      let fromPrev = prevEnd & " -> " & stmt.start & "[xlabel=no];\n" & stmt.body
      # if stmt.node.kind in @[cnkIf, cnkElif, cnkElse]:
      #   branches &= fromPrev
      # else:
      result &= fromPrev

      result &= stmt.final & " -> " & endWith & "[xlabel=yes];\n"

      prevEnd = stmt.start

    result = "//Child nodes for cond node at " &
      startWith &
      "\n{\nrank=same;\n" & branches & "}\n" & result

  else:
    for stmt in statements:
      result &= stmt.makeDotNode(stmt.start, true)
      result &= stmt.makeDotNode(stmt.final, false)
      result &= prevEnd & " -> " & stmt.start & ";\n" & stmt.body
      prevEnd = stmt.final

  result &= prevEnd & " -> " & endWith & ";\n"


proc scopeToGraph(scope: Scope): ScopeDescr =
  let start = scope.name & "_st"
  let final = scope.name & "_en"

  echo "converting scope ", scope.name
  echo scope.text

  let inner = case scope.node.kind:
    of cnkExpr, cnkAssgn:
      scope.text.joinScope(start, final)
    else:
      scope.children.mapIt(it.scopeToGraph()).joinScope(start, final, scope.node)

  let publicStart = case scope.node.kind:
    of cnkExpr, cnkAssgn: start & "_body"
    of cnkCond: scope.children[0].name & "_st"
    else: start

  let publicFinal = case scope.node.kind:
    of cnkExpr, cnkAssgn: start & "_body"
    else: final


  return ScopeDescr(
    start: publicStart,
    final: publicFinal,
    body: inner,
    node: scope.node
  )

func enumerate(scope: Scope): Scope =
  result = scope
  result.children = scope.children.enumerate()

proc scopeToDot(inScope: Scope): string =
  let scope = enumerate(inScope)
  let top = scopeToGraph(scope)
  let toplevel = Node(kind: cnkTerminal)
  joinScope(@[top], "start", "end", toplevel)

proc runTestCases() =
  let body: Option[Scope] = chartBuilder(
    "if (a) { int a = 0; } else if (c) { int c = 0; } else { int b = 0; };")
  if body.isSome:
    let conf = "splines=ortho;nodesep=1;ranksep=1;\n"
    let res = body.get.scopeToDot
    writeFile("graph.tmp.dot", "digraph G {\n" & conf & $res & "}")


# echo parse("for (;;) { while () {}}")

parseArgs:
  opt:
    name: "input-file"
    opt: ["--input", "+takes_value"]
    help: "Input file name"
  opt:
    name: "output-file"
    opt: ["--output", "+takes_value"]
    help: "output file name"
  opt:
    name: "test-line"
    opt: ["--test-line", "+takes_value"]
    help: "test single line"
  opt:
    name: "builtin-tests"
    opt: ["--builtin-tests"]
    help: "run builtin tests"
  opt:
    name: "debug-parse"
    opt: ["--debug-parse", "+takes_value"]
    help: "run debug parse on the statement"

if hasErrors:
  quit(1)


if "input-file".kp():
  let inputFile = "input-file".k.toStr()
  let outputFile = "output-file".k.toStr()
  # echo "Out file: ", outputFile
  # echo "In  file: ", inputFile

  # let inputString = readFile(inputFile).string

  # echo "In file content: \n\n", inputString

elif "test-line".kp():
  test("test-line".k.toStr())

elif "debug-parse".kp:
  let instr = "debug-parse".k.toStr
  let res = debugParse(instr)
  ceUserInfo2(&"parsing {instr}")
  if res > 0:
    showArrow("",instr, res, &"parse: ok ({res})")
  else:
    ceUserInfo0("parse: fail")

elif "builtin-tests".kp():
  runTestCases()
